import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from '@/context/authProvider'
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"
import {ThemeProvider} from '@/context/themProvider'
import NavBar from "@/components/public/NavBar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeProvider>
      <body className={inter.className}>
        <NavBar/>
        <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
          <div className="flex-1 flex flex-col h-full">{children}</div>
           <Footer/>
        </main>
       <Toaster/>
      </body>
     </ThemeProvider>
      </AuthProvider>
    </html>
  );
}
